### ISSUE TITLE
The app is super-slow

### ISSUE THREAD

**Issue by KnowledgeWanderer** [jeremykenedy/laravel-spa#161]
Hi there, I managed to get everything set up and most of it work really well, but the first paint takes from 10 seconds to even more at times, at every new page is really slow.

Is there a issue with all the debugging being enabled or what's going on? What load times do you get and how fast is the app working on your end?

I attached ss and I want to mention another thing, for example I'm in the admin menu, when I click Roles, after 5 seconds it redirects me back on the admin page, and if I click roles again is when I can use it.

![image](https://user-images.githubusercontent.com/40168248/214288461-68cacbc1-f305-4aad-ae4e-432ad08b4e70.png)

![Untitled](https://user-images.githubusercontent.com/40168248/214288780-c2fc7123-8a4b-4fcc-98b2-2213b38a13be.png)

Is this behavior normal?

**Comment by jeremykenedy** [comment]
Nope. See the demo as it runs fine.

**Comment by jeremykenedy** [comment]
It could be an environment issue, a caching issue (pho artisan confit:cache), or a vite confit issue with looking for an ssl possibly.
