### ISSUE TITLE
Socialite Login

### ISSUE THREAD

**Issue by jalilhadjhabib** [jeremykenedy/laravel-spa#226]
Hello when i click on the socialite button to login it tells me this error :

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'event')
![image](https://user-images.githubusercontent.com/101253359/227707584-1a324ef6-0a5d-4dcb-857c-f585d1c9e1c4.png)

analytics.js file : 

![image](https://user-images.githubusercontent.com/101253359/227707621-e231018d-f8df-4ae4-8760-31ee8b10c61e.png)

**Comment by jeremykenedy** [comment]
Cannot replicate.
