### ISSUE TITLE
Signup

### ISSUE THREAD

**Issue by jalilhadjhabib** [jeremykenedy/laravel-spa#228]
Hi, when i try to signup it shows me this error
![image](https://user-images.githubusercontent.com/101253359/227769138-617a81ea-8d8f-4040-a5a7-2d9de82d71ee.png)

but it still created the account and received the email verification. it doesnt redirect after that
![image](https://user-images.githubusercontent.com/101253359/227769211-f17210b8-1f0c-40cf-ad79-65f4f3d9c8f1.png)

**Comment by jeremykenedy** [comment]
Cannot replicate. You keep opening issues. You have to take some initiative and do the programming and learning yourself.
