### ISSUE TITLE
app url and https

### ISSUE THREAD

**Issue by leonpug** [jeremykenedy/laravel-spa#309]
Hi,
set APP_URL=http://spa.test (also set SANCTUM_STATEFUL_DOMAINS=http://spa.test) in .env file.
but request mix http and https with errors:

![Immagine1](https://github.com/jeremykenedy/laravel-spa/assets/54739530/8ca2b9b6-8071-4d69-a7ed-439836100fa5)

(my dev env is http only)
how can i fix it?

thanks

**Comment by jeremykenedy** [comment]
You probably need to clear your cache and rebuild the config with 'php artisan cache:clear'
